reset (reset (1 + reset ((fun y -> control h -> y)
                         (control f -> control g -> 2 + f 5))))

(* < < 1 + < (λy. Fh. y) (Ff. Fg. 2 + f 5) > > > *)
(* < < 1 + < Fg. 2 + f 5 > > > where f = λx. (λy. Fh. y) x *)
(* < < 1 + < 2 + f 5 > > > where g = λx. x *)
(* < < 1 + < 2 + (λy. Fh. y) 5 > > > *)
(* < < 1 + < 2 + Fh. 5 > > > *)
(* < < 1 + < 5 > > > where h = λx. 2 + x *)
(* 6 *)
